server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8083/eureka/,http://peer2:8084/eureka/
spring:
  application:
    name: eureka-client

#开启熔断
feign:
  hystrix:
    enabled: true