server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8083/eureka/,http://peer2:8084/eureka/
spring:
  application:
    name: eureka-client
#链路追踪配置
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:8089
#开启熔断
feign:
  hystrix:
    enabled: true