server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8083/eureka/,http://peer2:8084/eureka/
spring:
  application:
    name: eureka-zuul
#/cilent1/**中  ** 代表eureka-client中的路径，如果要访问eureka-client，必须加前缀cilent1
zuul:
  routes:
    client1api:
      path: /cilent1/**
      serviceId: eureka-client
    client1ap2:
      path: /cilent2/**
      serviceId: eureka-client2