server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8083/eureka/,http://peer2:8084/eureka/
spring:
  application:
    name: eureka-client2
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:8089