##两个注册中心相互注册必须满足：
#1：eureka.client.serviceUrl.defaultZone配置项的地址，不能使用localhost，要使用peer1之类的域名，通过host映射到127.0.0.1；
#2：spring.application.name或eureka.instance.appname必须一致；
#3：相互注册要开启：
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
##
spring:
  application:
    name: eureka-service

server:
  port: 8083
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer2:8084/eureka/
